/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Example: typeof import('./components/Example.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    IconMdiTick: typeof import('~icons/mdi/tick')['default']
    Tree: typeof import('./components/Tree.vue')['default']
  }
}
